### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by ianfp** [doctrine/annotations#116]
Version 1.3.0 bumped the minimum PHP version to 5.6, which is a BC-break (right?). This should have resulted in a major version change.

It's annoying to do a `composer install` on the server and see
```
Problem 1
- Installation request for doctrine/annotations v1.3.1 -> satisfiable by doctrine/annotations[v1.3.1].
- doctrine/annotations v1.3.1 requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
```

**Comment by Ocramius** [comment]
Hey @ianfp!

 > which is a BC-break (right?)

This is a common misconception: that's not the case, since the API of this package didn't change. See https://github.com/mojombo/semver/issues/148 (http://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api)

 > It's annoying to do a `composer install` on the server and see

That's actually good! This means that you correctly committed your `composer.lock`, and composer is preventing an upgrade on purpose. Still, you are updating dependencies in an environment that does not reflect your production one.

Closing this as `invalid`.

**Comment by ianfp** [comment]
I wondered if it was something like that... thanks for the link!
