### ISSUE TITLE
Memory leak in AnnotationRegistry::registerLoader() when called multiple times

### ISSUE THREAD

**Issue by TriAnMan** [doctrine/annotations#145]
If we call AnnotationRegistry::registerLoader() multiple times we've got an self::$loaders array growing indefinitely.

Consider to append self::$loaders with a keyed value.

A key for callable can be determined by spl_object_hash() for anonymous functions and by a combination of md5() and spl_object_hash() for other types of callable.

I can provide a non BC breaking PR for this issue if interested.

**Comment by alcaeus** [comment]
@TriAnMan if you are referring to registering the same loader multiple times, this was fixed in #137.

**Comment by stof** [comment]
@Ocramius idea: optimize the case where `AnnotationRegistry::registerLoader('class_exists')` is called repeatedly: if the loader being registered is `class_exists` and the last loader in the array is also `class_exists`, skip the registration (checking only the last loader rather than any loader is here to avoid breaking BC regarding re-registering the loaders in a different order. Registering `class_exists` twice in a row won't have any difference to a single registration, unless your PHP autoloader is accepting to load the class only on the second call, but then your PHP project is already pure madness).

Registering anything else than `class_exists` should be considered deprecated to allow getting rid of this AnnotationRegistry non-sense in 2.0. The registry is here just because popular pre-Composer autoloading libraries were regularly breaking `class_exists` in case of miss, including Doctrine Common (yeah, Doctrine Common was hurting itself during years) and ZF 1. Supporting the case of autoloaders breaking in case of miss is not worth it IMO (having a non-functional `class_exists` function is likely to break other parts of the project anyway).

@alcaeus no. #137 does not prevent the list of loaders to grow. It optimizes the performance of the usage of these loaders.

**Comment by stof** [comment]
Note that registering `class_exists` repeatedly actually happens when running tests in Symfony with a recent PHP version: to hide this AnnotationRegistry non-sense from users, Symfony registers the loader automatically at the time the annotation parser is instantiated by the DI container.
But in the testsuite, each test would run with its own container, and so the registration could happen again when the service gets instantiated by the second test (and the third one, etc...). If you have lots of tests, the `AnnotationRegistry::$loader` variable becomes huge (with the same `class_exists` value many time in it). And this leaks memory.

**Comment by stof** [comment]
Btw, we could make the implementation a bit more generic (avoiding to tie it to the `class_exists` recommendation): make a strict comparison between the last registered loader and the new loader, and skip the registration (the duplicate `class_exists` is just a special case of it then).

**Comment by Ocramius** [comment]
@stof moving the registration to the loader with a new method (`::registerLoaderIfNotExists()`) would be better and would avoid BC issues.

**Comment by TriAnMan** [comment]
@Ocramius 
I think it will be hard to make `::registerLoaderIfNotExists()` working together with `::registerLoader()` because `registerLoaderIfNotExists` have to deal with the same ::$loaders array.

So this array should be keyed to make `registerLoaderIfNotExists` work and to not break BC for `registerLoader` keys have to be composite like `$hash . $hashIterationNum`. So if registerLoader is called twice for the same $hash $hashIterationNum increases.
Thus registerLoaderIfNotExists must check only $hash part of the key.

I believe this is the only way not to brake the code that relies on sequential registration of the same autoloader. But as for me I can't imagine such code to be useful.

**Comment by Ocramius** [comment]
@TriAnMan if the callers just use `registerLoaderIfNotExists()` or `registerImplicitLoader()` then it is fine. You just need to get rid of `registerLoader` calls in consumers.

**Comment by stof** [comment]
Well, adding a new method would make things harder (Symfony cannot just use always the new method, due to latest version of the library requiring PHP 7.1 and so Symfony 3.x has to keep support for older versions).
The BC issue you highlighted before was related to the order of loaders when registering them again later. But unless people are doing random loaders (and then, the usage of the `class_exists(..., false)` optimization already broke BC for them), things are fine if you avoid calling the same loader twice in a row.

**Comment by Ocramius** [comment]
I'm not worried about symfony's schedule here: I'm just worried about
providing a new BC compliant solution/improvement. Whether symfony can use
it or not is a separate concern.

**Comment by stof** [comment]
Well, my proposal is BC, unless for cases where people are doing crazy things to check for existence. But the `class_exists(..., false)` optimization is not safe either for these crazy things.

**Comment by sstok** [comment]
Can't Symfony create it's own loader? (as BC when using the newer method is not possible).
The implementation of this class seems rather simple.

**Comment by stof** [comment]
which loader ? The loader registered by Symfony is `class_exists`, so that loading happens with the PHP autoloading stack.
And the memory leak issue is not in the loader. It is in the registry.
And if you refer to the registry, no it cannot. The doctrine/annotation codebase would still be using the Doctrine class when doing static calls, not the new class you ask us to create.

**Comment by Ocramius** [comment]
Handled in #162
