### ISSUE TITLE
Whre are the annotation classes?

### ISSUE THREAD

**Issue by tzfrs** [doctrine/annotations#184]
Hi,

sorry if I'm misunderstanding but according to http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/annotations-reference.html#annotations-reference states

> The implementation of these enhanced docblock annotations is located in the Doctrine\Common\Annotations namespace and therefore part of the Common package

the annotations like `Entity`, `Table`, `Column` etc. should be part of the doctrine/common package.

So I did `composer require doctrine/common:^2.8.1` and now wanted to use these Annotations on my Entities, however the classes don't exist? 

When using doctrine in Symfony, I can simply 

`use Doctrine\ORM\Mapping as ORM;`

and then use `@ORM\Entity`, etc. but these classes are in the `Doctrine\ORM\Mapping` namespace, not in the annotation namespace, so I think either I'm misunderstanding something or the documentation has an error?

But since doctrine is such a big project i'd think that I'm misunderstanding sth, because otherwise this must have been noticed by someone.

**Comment by alcaeus** [comment]
"The implementation of these enhanced docblock annotations" refers to the annotation parsers and all other classes necessary to support annotations. The actual mapping annotations (e.g. `Entity`, `Table`, `Column`, etc.) are defined in `doctrine/orm` since they are only valid for ORM. MongoDB ODM for example brings its own `Document`, `Field` and `Reference*` annotations.

**Comment by tzfrs** [comment]
Ah, so as expected, just a misunderstanding on my site. Thanks for the fast answer, will require `doctrine/orm` as well then.
