### ISSUE TITLE
Consider PSR-6/PSR-16 abstraction for caching

### ISSUE THREAD

**Issue by Majkl578** [doctrine/annotations#204]
Instead of depending on Doctrine Cache interface directly, it would be nice to depend on PSR-6/PSR-16 interface instead.
That would allow us to transparently support Doctrine Cache 2.0 (when it comes), Symfony Cache component etc.
Huge downside of PSR interfaces is that it's untyped PHP 5 code, but benefits of abstraction may still prevail.

**Comment by Ocramius** [comment]
I'd probably leave the entire caching story completely out of the package here.

**Comment by Majkl578** [comment]
That might be a bit inconvenient for lots of consumers - not everyone is using full stack frameworks like Symfony that provide integration/setup out of box. :|
The cost of abstracting CachedReader through PSR-16 would probably by very low as Cache implementation would always be delegated to 3rd party.

**Comment by Ocramius** [comment]
The memoizing of the actual annotations is marginally useful, as the user already went through the whole reflection and autoloading mumbo-jumbo, and already lost a lot there. What is more interesting is the configuration resulting from that, which is not the annotations themselves.

I think we should simply get rid of this concern in the package, since writing a `Reader` implementation that is also memoized is trivial and better left to third parties (it's a [simple interface](https://github.com/doctrine/annotations/blob/46cce2e385b611b37c5d306d5c27c9879e2f4822/lib/Doctrine/Annotations/Reader.php), while the reduced dependencies would be a good riddance for frameworks that already abstract away the memoized DSL that comes much after the annotations have been parsed.

Composing a caching layer with annotations directly, especially considering the amount of libraries depending on `doctrine/annotations`, drags in a lot of stuff that most consumers don't even want to know anything about.
