### ISSUE TITLE
[feature] Group annotation

### ISSUE THREAD

**Issue by ivan1986** [doctrine/annotations#225]
When you use a lot of annotations it's look like this

```
    /**
     * @Serializer\Expose()
     * @Serializer\Type("integer")
     * @Serializer\Groups({"Editor"})
     * @Assert\NotBlank()
     * @ORM\Column(type="integer")
     */
    protected $val1;
```

And if there are several fields of the same type, all summaries must be applied to each field

```
    /**
     * @ODM\EmbedOne(targetDocument="App\Models\Product\Lang")
     * @JMS\Type("App\Models\Product\Lang")
     * @var Lang
     */
    public $description;
    /**
     * @ODM\EmbedOne(targetDocument="App\Models\Product\Lang")
     * @JMS\Type("App\Models\Product\Lang")
     * @var Lang
     */
    public $hours_operations;
    /**
     * @ODM\EmbedOne(targetDocument="App\Models\Product\Lang")
     * @JMS\Type("App\Models\Product\Lang")
     * @var Lang
     */
    public $duration;
```

I would like to see such a possibility

```
/**
 * @GroupAnnotation()
 */
final class LangField
{
    /**
     * @ODM\EmbedOne(targetDocument="App\Models\Product\Lang")
     * @JMS\Type("App\Models\Product\Lang")
     */
    public $field;

}

/**
 * @GroupAnnotation(params={'type'})
 */
final class EditorField
{
    /**
     * @Serializer\Expose()
     * @Serializer\Type("$type")
     * @Serializer\Groups({"Editor"})
     * @Assert\NotBlank()
     * @ORM\Column(type="$type")
     */
    public $field;

}
```

usage

```
    /**
     * @EditorField(type="integer")
     */
    protected $val1;


    /**
     * @LangField
     * @var Lang
     */
    public $description;
    /**
     * @LangField
     * @var Lang
     */
    public $hours_operations;
    /**
     * @LangField
     * @var Lang
     */
    public $duration;

```

**Comment by Majkl578** [comment]
FWIW this type of _meta annotations_ doesn't belong to Doctrine Annotations itself, at least in my opinion.

**Comment by alcaeus** [comment]
> FWIW this type of _meta annotations_ doesn't belong to Doctrine Annotations itself, at least in my opinion.

I agree.

@ivan1986 FWIW, starting with version 1.2.0 (which was released in 2014), annotations support the `::class` constant. So, taking one of your examples:
```php
    /**
     * @ODM\EmbedOne(targetDocument="App\Models\Product\Lang")
     * @JMS\Type("App\Models\Product\Lang")
     * @var Lang
     */
    public $description;
```

This could be simplified to
```php
    /**
     * @ODM\EmbedOne(targetDocument=Lang::class)
     * @JMS\Type(Lang::class)
     * @var Lang
     */
    public $description;
```

For one, the annotations become much more concise since you no longer have to use the FQCN of the class in question. Even better than that, tooling can actually work with these identifiers since this is no longer any string constant. For example, PhpStorm with the annotations plugin will show annotation usages of `Lang` when using the "Find Usages" feature and will also be able to apply refactorings (such as "Rename class" or "Rename namespace", saving you lots of manual work.

Regarding the other examples you specified, these are completely different from what annotations actually do: a class defines an annotation with its public properties defining options. Any logic associated with the annotation is taken care of whoever consumes these annotations, e.g. mapping drivers in ODM or JMSSerializer. With this change, you suggest moving this logic into the annotations library, which is definitely not feasible: all of a sudden the library would have to know that a specific annotation needs to be treated as several other annotations that may have similar or conflicting options that users may want to specify.

As such, I would suggest to close this issue. If you want to avoid defining multiple annotations (e.g. a field mapping for ODM and a type mapping for JMSSerializer), write a metadata driver for one or the other tool that knows about the other metadata. For example, if your serialiser metadata driver knows about ODM metadata, the type could easily be inferred from the field mapping.

**Comment by ivan1986** [comment]
Hmm, I rather represented this function as a C ++ template or C macro in the context of annotations for grouping several libraries that use annotations.

Well, actually for me this problem is no longer relevant.
