### ISSUE TITLE
this library doesn't read annotation from parent class level annotations

### ISSUE THREAD

**Issue by videni** [doctrine/annotations#233]
Doctrine generate a proxy for my organization entity, `Proxies\__CG__\App\Bundle\OrganizationBundle\Entity\Organization`. 

```
use App\Bundle\FileBundle\Annotation as FileAnnoation;

/*
 * @FileAnnoation\File()
 */
class Organization
{
}
```

it gives me no `File` annotation defined,  when I try to check whether the organization proxy object  has `File` annotation.

is this expected behavior? I didn't find any document about this.

**Comment by Ocramius** [comment]
>  when I try to check the organization proxy object has `File` annotation.

Can you please check this again? Proxies should:

 1. not be scanned for annotations (it's generated code - unreliable for metadata extraction) 
 2. not have annotations at all (the generated code should have very minimal comments)

**Comment by videni** [comment]
@Ocramius, thanks for quick reply. even it is a proxy object, I need to know whether its parent class Organization has  `File` annotation defined. how do I do this please?

**Comment by Ocramius** [comment]
Annotations are not inherited, so you will need the real class name first. See how the [`AbstractClassMetadataFactory` does it](https://github.com/doctrine/persistence/blob/3a6c468aaf9897fc7117b1301508ee23b6fe3c05/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php#L401-L413).

Closing here, since this is not an issue of the annotations library: incorrect reflection instance was given to the annotation reader.

**Comment by videni** [comment]
@Ocramius , thanks a lots
