### ISSUE TITLE
AnnotationRegistry is deprecated but has no alternative in v1.6.1

### ISSUE THREAD

**Issue by danepowell** [doctrine/annotations#270]
I understand that the AnnotationRegistry is being deprecated and in version 2+ we should just rely on the Composer autoloader, which is awesome.

However, it seems that at least in version 1.6.1, you can't just use the autoloader, you still _must_ use the registry. I think it's wrong to mark the registry members as deprecated when no better alternative exists today. This causes a lot of confusion amongst users and makes downstream deprecation tests somewhat useless, since there's no way to get them to pass today.

I think that version 1.x should be changed to allow using the autoloader for folks that don't want to use the deprecated functions.

**Comment by Ocramius** [comment]
The idea is that there will be no need to use autoloading at all. We can't
provide an alternative as there ain't any: pre-existing autoloading will
deal with this.

**Comment by danepowell** [comment]
Yeah I'm excited that that's the vision for v2, but the problem is that everything's already been deprecated in v1 and there's no alternative in v1. Correct me if I'm wrong.

In my mind, the main point of having deprecation warnings is to give folks time to effect a transition between two versions of an upstream library such as annotations. The way that functions have been deprecated in v1.6.1 without providing any viable alternative (that's usable in v1.6.1) subverts that whole purpose. It means that downstream projects will need to be much more tightly coupled to the annotation library version.

**Comment by Ocramius** [comment]
Yes, that is correct: specifically, "application" packages will, since libraries have no business in touching the annotation registry.

**Comment by sanmai** [comment]
> libraries have no business in touching the annotation registry

Libraries do have a business in touching the annotation registry because a typical library is supposed to work out of box. Just `composer install ...` should be enough. 

And if you have to ask your users to add `AnnotationRegistry::registerLoader('class_exists')` whenever they want to use your library, that is the bad design. Guess what, nobody's going to do that because not a single sane person is willing to read the installation instructions beyond `composer install`.

Overall this is just calling for trouble and endless issues riddled with semantical errors about some inexistent annotations that seeming have nothing to do with the library they're trying to use. So we, as responsible library authors, have to deal with the annotation registry.

**Comment by scaytrase** [comment]
Looks like #271 solves the problem keeping BC. Can we adopt this?
