### ISSUE TITLE
Json Array Value Parse Error

### ISSUE THREAD

**Issue by LinkedDestiny** [doctrine/annotations#359]
Example Code:

```php
class Foo
{
    /**
     * @MyAnnotation(myProperty={"result":[1，2，3]})
     */
    private $bar;
}

/**
 * Class MyAnnotation
 * @Annotation
 */
final class MyAnnotation
{
    public $myProperty;
}

use Doctrine\Common\Annotations\AnnotationReader;

$reflectionClass = new ReflectionClass(Foo::class);
$property = $reflectionClass->getProperty('bar');

$reader = new AnnotationReader();
$myAnnotation = $reader->getPropertyAnnotation($property, MyAnnotation::class);

var_dump($myAnnotation->myProperty);
```

I wish:
```json
{"result":[1, 2, 3]}
```
parsed into array 

```php
$myproperty = [1,2,3];
```

But I got an error like:

```
[Syntax Error] Expected PlainValue, got '[' at position 35 in property Foo::$bar
```

It means that parser do not suppert json array parse.

so how can i solve my problem?

**Comment by bradjones1** [comment]
I ran into this today. Turns out that square brackets are a no-go in doctrine annotations, and even if you try to stringify them, you can't escape them so it's a hard prohibition on `[` and `]` as far as I can tell.

Drupal's json-rpc module has annotation parameters which may include JSON schema; the approach there is to [express them in PHP, essentially](https://www.drupal.org/project/jsonrpc/issues/3269347), and then parse them accordingly in your code once they're passed on to the annotation object's attributes.

For instance, write your schemas like

```
 *       schema = {"type" = "string", "enum" = {"google", "apple"}},
```
(notice the `{}` syntax for an array.)

**Comment by LinkedDestiny** [comment]
Got it，thx
